### ISSUE TITLE
fail to submit

### ISSUE THREAD

**Issue by jenbrannstrom** [qualifiedleads/oca-bxl#4]
http://prntscr.com/q5ixfk

Submitting webform is failing

**Comment by aviox-git** [comment]
@jenbrannstrom  when i submit for it takes me to this page https://www.oxfordcapacityanalysis.org/
Is it correct? if not where it should take me too?
![Free Personality Test - Oxford Capacity Analysis - Church of Scientology](https://user-images.githubusercontent.com/47270302/70054146-f4ba1880-15fc-11ea-86d4-4fe2da1cd4f3.png)

**Comment by KNLopez** [comment]
Hi Jen, this one might be caused by an ad-blocker? The submission seems to be fine. As OCA Started and OCa id was logged. Sent from Mail for Windows 10 From: Jen BrannstromSent: Tuesday, December 3, 2019 7:34 PMTo: qualifiedleads/oca-bxlCc: SubscribedSubject: [qualifiedleads/oca-bxl] fail to submit (#4) http://prntscr.com/q5ixfkSubmitting webform is failing—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by jenbrannstrom** [comment]
> Hi Jen, this one might be caused by an ad-blocker? The submission seems to be fine. As OCA Started and OCa id was logged.

@KNLopez  : I think you might be right!
