### ISSUE TITLE
data not arriving in G Sheet

### ISSUE THREAD

**Issue by jenbrannstrom** [qualifiedleads/oca-bxl#5]
This[ commit](https://github.com/qualifiedleads/oca-bxl/commit/87fdd00da509cc417ed2da7068df0c21605c037b)
submits data apparently, and passes the user to the correct website.
However no data arrives at https://docs.google.com/spreadsheets/d/1sSOyrtXPRHhdVSwhGgO80TWBG39Lb7Fp21HcQd-gMcI/edit#gid=1856342821
@aviox-git I have given you access to the sheet

Does [this ](https://stackoverflow.com/questions/32077888/spreadsheetapp-openbyurl-and-openbyid-give-errors)have something to do with it

**Comment by aviox-git** [comment]
Hello @jenbrannstrom 

I am checking this now.

**Comment by KNLopez** [comment]
Hi Jen, was this resolved? I checked this yesterday and it seems like the gid doesn’t match on the script file. Sent from Mail for Windows 10 From: Jen BrannstromSent: Thursday, January 9, 2020 6:51 AMTo: qualifiedleads/oca-bxlCc: SubscribedSubject: [qualifiedleads/oca-bxl] data not arriving in G Sheet (#5) This commitsubmits data apparently, and passes the user to the correct website.However no data arrives at https://docs.google.com/spreadsheets/d/1sSOyrtXPRHhdVSwhGgO80TWBG39Lb7Fp21HcQd-gMcI/edit#gid=1856342821@aviox-git I have given you access to the sheetDoes this have something to do with it—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
